name: Basic Code Quality

on: [push]

env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install flake8
        run: pip install flake8
      - name: Flake8
        run: flake8 --count .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install poetry
        run: pip install poetry
      - name: Install repo
        run: poetry install --no-interaction --no-ansi
      - name: mypy
        run: mypy .

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install black
        run: pip install black
      - name: Check code formatting with black
        run: black --check .

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install poetry
        run: pip install poetry
      - name: Install repo
        run: poetry install --no-interaction --no-ansi
      - name: Check import formatting with isort
        run: isort --check-only --diff .

  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install detect secrets
        run: pip install detect-secrets
      - name: Look for secrets
        run: git ls-files -z | xargs -0 detect-secrets-hook -v
